goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.Uri', 'goog.object', 'goog.math.Integer', 'goog.string.StringBuffer', 'goog.array', 'goog.math.Long']);
goog.addDependency("../process/env.js", ['process.env'], ['cljs.core']);
goog.addDependency("../oops/config.js", ['oops.config'], ['cljs.core']);
goog.addDependency("../oops/helpers.js", ['oops.helpers'], ['cljs.core']);
goog.addDependency("../oops/state.js", ['oops.state'], ['oops.config', 'oops.helpers', 'cljs.core']);
goog.addDependency("../oops/schema.js", ['oops.schema'], ['cljs.core']);
goog.addDependency("../oops/messages.js", ['oops.messages'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../clojure/walk.js", ['clojure.walk'], ['cljs.core']);
goog.addDependency("../cljs/spec/gen/alpha.js", ['cljs.spec.gen.alpha'], ['cljs.core']);
goog.addDependency("../cljs/spec/alpha.js", ['cljs.spec.alpha'], ['cljs.core', 'goog.object', 'clojure.string', 'clojure.walk', 'cljs.spec.gen.alpha']);
goog.addDependency("../oops/sdefs.js", ['oops.sdefs'], ['cljs.core', 'cljs.spec.alpha']);
goog.addDependency("../oops/core.js", ['oops.core'], ['oops.config', 'oops.state', 'oops.helpers', 'cljs.core', 'oops.schema', 'goog.object', 'oops.messages', 'oops.sdefs', 'cljs.spec.alpha']);
goog.addDependency("../czlab/elmo/afx/ecs.js", ['czlab.elmo.afx.ecs'], ['cljs.core', 'oops.core']);
goog.addDependency("../czlab/elmo/afx/test.js", ['czlab.elmo.afx.test'], ['cljs.core', 'czlab.elmo.afx.ecs']);
